language: python
python:
- '3.7'
before_install:
- set -e
- ". $HOME/.nvm/nvm.sh"
- nvm install 13.7.0
- nvm use 13.7.0
- rm -rf node_modules
- npm install
- sudo -H pip install --upgrade setuptools
- sudo -H pip install --upgrade pip wheel requests pyopenssl
- sudo -H pip install --ignore-installed six
- sudo -H pip install --upgrade tox twine
- pip install --upgrade setuptools
- pip install --upgrade aiohttp requests cryptography pyopenssl
- pip install ccxt
- pip2 install requests[security]
- git pull --tags
- pecl install ds
- php -i | grep php.ini
- sudo ls -alh /home/travis/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/no-debug-zts-20170718/
- sudo tail /home/travis/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- composer install
script:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
  npm config set git-tag-version=false && NPM_VERSION=$(npm version patch); fi
- cp package.json README.md LICENSE.txt keys.json python
- npm run build
- npm run test-base
- bash -c 'node run-tests --js --python --verbose 7' 2>&1
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then env COMMIT_MESSAGE=${NPM_VERSION:1} GITHUB_TOKEN=${GITHUB_TOKEN} ./build/push.sh; fi
after_failure:
- dmesg | grep -i kill
- sleep 4
notifications:
  slack:
    secure: ktACBU+k1AL0SXKHKNcEkWjx5Tha7OWyO1YeirwDxnQiI1KPfgs0sx8FenzBuH9imob3fU4DSpftIC9Zpa9pRIyKApIOMw3aGG4tY8DYiV7zTaHxs4GKHug2BdUG+U2/h6iaulS7CxiqVf9/6aZFMhYT+Dl3tbof0+Xin9OKXLc2QGSgjzHoxBu1FrHEMIqcoKzKHP7PHWTY7xSDvBHwuf4waAmXxuAw91xOCzYCteTcNS0vlHsP+fBlw7thySsn0T4ZDIjLYnlDacUbYeUXjJ2akzOSfd1+v53gVW5C9+3LoXwdUw35kGG/NSetdvxXt36dtdYRNRoX33hwxIoizP7MoIhQ2x7i9Q6hnT7N05Eu4xuYfIQrTcoD+2LWYtOYRjRJuJnHf9cI/vwSXii+P+ESXpTACjszREA/JvpL/WTUOXkbdgsubVLahCkLF6fab1zs/kNzQY//aw4P60v50hcNawenbMkhKyz5KXCsePyc+6rCgVJWYaontfjPudj4xmdpD9F87steboS6HVkYC/ED+D6XyC+MyDi3MjJ/RJ7OV0f+eZO7UoLFWvQPuv3bkUa8VhQjjiyrdNVOEIgUGhJ/OT//88aIWW2Qr4IaQulqAyUFQJd4NhbJuQbIr4vnJu0MEAVND6zM1fdRyS3LnncmPya/XhnnEQBkqLBfaFg=
env:
  global:
    secure: bH1hHeIbP6cwEFa3aYOch+sIaBsU+jFVDlVDxwJc4I4KC79OQWqkVqnNKzr+BNFUHi9IytOJ8ytu5+2imoaFCTJ+OpOZT3qX+kL8G0DSLLZrwx9NP8LtINfJM71w3V1t4Maww0PRakVksexZ5y62IjU0bPG9BmhmDsuSFimWlAgoGW0PtmhiX0nSxvF4cWqr1zdfCBg63+rmFzJcZGBU7Z/IE94X/SIoO9BvqzVcPrVaWFNy3+DoxbX2qEyNk0hpuMEgXjGubG0n/UWogIj71/h9K8SyRu561GWTf4OGA8eU/lJNwRFNNwljA2/DFVRK+xp5lIp4eFUK44XAVEcB3Y3z4/r2pSgfW5X9ZRI5/BgC3uawa0k53M3Nd+3HOY2PGe1XAIMoHO2rgZag/+IpXRkaKdrYC5jMwBWg5hoBjjXlaH33i7fmdACFFsHkDBUW0IHu5u0N4HNUBeFkd3AahRR2JyWbIx9fId8Sd8r2IqibiaLS61Y6NhNohQ1oWY+jWvmF5Fky1gDE+3p8xTcxNcsCa+2x32KqqQuN4f9RScCsV9SjDd4rHU/0b4Jyhvjd0nj0L6xXPfhzJPC1KYfJZAXa27dmuhXtC00IInVNL6SCVqICQyiG1KKdVOlkj7UZ/dfX37/mt381TqrWdC7bzOMYdcLRmrIuga3x2qTeudE=
